url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
lang: "ua" # lang
title: "3DCopy" # the name of your site, e.g. ACME Corp.
copyright_notice: "© 2025 3DCopy.space. All rights reserved."



